### ISSUE TITLE
Java - Quarkus

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/otel-java-instrumentation#10]

**Comment by arik-dig** [comment]
added PR to Quarkus main branch [Feature/OTEL JAX-RS Span Code function](https://github.com/quarkusio/quarkus/pull/29939).
waiting for them to review and merge it

**Comment by arik-dig** [comment]
I've created a new PR [Feature/OTEL JAX-RS (Resteasy) Span Code function](https://github.com/quarkusio/quarkus/pull/30073), waiting for review and merge it.

**Comment by arik-dig** [comment]
PR been merged, and will be part of quarkus 2.16
