### ISSUE TITLE
Java - Auto Instrumentation

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/otel-java-instrumentation#9]

**Comment by arik-dig** [comment]
supporting the following :

* [Feature/Digma agent instrumentation for spring-mvc](https://github.com/digma-ai/otel-java-instrumentation/pull/12)
* [Feature/agent instrumentation of JAX-RS](https://github.com/digma-ai/otel-java-instrumentation/pull/13)
* [Feature/Digma java agent extension + resources](https://github.com/digma-ai/otel-java-instrumentation/pull/11)
